services:
  - name: service-a
    type: token
    key: "abcd1234"
    valid: true
    allowed_rps: 20
    wait_time_if_limit_exceeded: "10s"

  - name: service-b
    type: token
    key: "efgh5678"
    valid: false
    allowed_rps: 30
    wait_time_if_limit_exceeded: "5s"

  - name: service-c
    type: token
    key: "ijkl91011"
    valid: false
  